from app import Vehicle, app, db

# Sample vehicles data
sample_vehicles = [
    {
        "garage_number": "1",
        "brand": "ГАЗ 3302",
        "driver": "Гуринович А.В.",
        "gos_number": "АВ 6100-4",
        "capacity": 1500.0,  # kg
        "length": 3.0,  # m
        "width": 1.9,
        "height": 2.6,
        "status": "free",
    },
    {
        "garage_number": "3",
        "brand": "VOLKSWAGEN",
        "driver": "Герко К.Р.",
        "gos_number": "6039 МЕ-4",
        "capacity": 2000.0,
        "length": 4.7,
        "width": 1.9,
        "height": 2.0,
        "status": "free",
    },
    {
        "garage_number": "4",
        "brand": "ГАЗ 2705",
        "driver": "Артеменко В.И.",
        "gos_number": "AI 5870-4",
        "capacity": 1350.0,
        "length": 3.1,
        "width": 1.8,
        "height": 2.3,
        "status": "busy",
    },
    {
        "garage_number": "7",
        "brand": "ГАЗ 3302",
        "driver": "Клевцов Ю.В.",
        "gos_number": "АВ 6100-4",
        "capacity": 1500.0,
        "length": 3.0,
        "width": 1.9,
        "height": 2.6,
        "status": "free",
    },
    {
        "garage_number": "8",
        "brand": "ГАЗ А22R23",
        "driver": "Докурно Р.М.",
        "gos_number": "АМ 7485-4",
        "capacity": 1200.0,
        "length": 2.3,
        "width": 2.5,
        "height": 2.8,
        "status": "free",
    },
    {
        "garage_number": "9",
        "brand": "GEELY",
        "driver": "Поцелуйко Д.А.",
        "gos_number": "4249 МР-4",
        "capacity": 5000.0,
        "length": 6.0,
        "width": 2.4,
        "height": 2.5,
        "status": "free",
    },
    {
        "garage_number": "10",
        "brand": "GEELY",
        "driver": "Зинкевич М.М.",
        "gos_number": "4257 МР-4",
        "capacity": 5000.0,
        "length": 6.0,
        "width": 2.4,
        "height": 2.5,
        "status": "free",
    },
    {
        "garage_number": "14",
        "brand": "ГАЗ 2705 ",
        "driver": "Перепечкин Е.А.",
        "gos_number": "AI 5871-4",
        "capacity": 1350.0,
        "length": 3.1,
        "width": 1.8,
        "height": 2.3,
        "status": "free",
    },
    {
        "garage_number": "16",
        "brand": "МАЗ 437143",
        "driver": "Жданюк В.В.",
        "gos_number": "АВ 7555-4",
        "capacity": 4200.0,
        "length": 5.3,
        "width": 2.4,
        "height": 2.3,
        "status": "free",
    },
    {
        "garage_number": "17",
        "brand": "МАЗ 5440 А5",
        "driver": "Гулецкий А.Э.",
        "gos_number": "АМ 0425-4",
        "capacity": 10100.0,
        "length": 13.6,
        "width": 2.45,
        "height": 2.3,
        "status": "free",
    },
    {
        "garage_number": "22",
        "brand": "ГАЗ А65R52",
        "driver": "Ерман В.Г.",
        "gos_number": "АН 7568-4",
        "capacity": 1500.0,
        "length": 6.9,
        "width": 2.0,
        "height": 2.8,
        "status": "free",
    },
    {
        "garage_number": "12",
        "brand": "МАЗ 437043",
        "driver": "Кособудский В.А.",
        "gos_number": "7349 АВ-4",
        "capacity": 4650.0,
        "length": 6.2,
        "width": 2.4,
        "height": 2.5,
        "status": "free",
    },
    {
        "garage_number": "26",
        "brand": "ГАЗ А31 R32-580",
        "driver": "Кайрис В.И.",
        "gos_number": "АМ 1153-4",
        "capacity": 1000.0,
        "length": 3.6,
        "width": 1.8,
        "height": 1.9,
        "status": "free",
    },
    {
        "garage_number": "290",
        "brand": "МАЗ 5340 В5",
        "driver": "Вишняк И.И.",
        "gos_number": "4925-4 АК",
        "capacity": 11000.0,
        "length": 6.1,
        "width": 2.45,
        "height": 3.4,
        "status": "free",
    },
    {
        "garage_number": "32",
        "brand": "МАЗ 5440 С9",
        "driver": "Граматовский В.И.",
        "gos_number": "АМ 9310-4",
        "capacity": 44000.0,
        "length": 6.1,
        "width": 2.5,
        "height": 4.0,
        "status": "free",
    },
    {
        "garage_number": "33",
        "brand": "ГАЗ А31 R33",
        "driver": "Шапель А.М.",
        "gos_number": "АМ 4491-4",
        "capacity": 1045.0,
        "length": 3.6,
        "width": 1.8,
        "height": 2.0,
        "status": "free",
    },
    {
        "garage_number": "34",
        "brand": "МАЗ 544028",
        "driver": "Клакевич И.Н.",
        "gos_number": "АМ 9397-4",
        "capacity": 18000.0,
        "length": 13.6,
        "width": 2.45,
        "height": 4.0,
        "status": "free",
    },
    {
        "garage_number": "35",
        "brand": "ГАЗ А31 R32",
        "driver": "Воронович С.Ч.",
        "gos_number": "АН 5280-4",
        "capacity": 1100.0,
        "length": 3.6,
        "width": 1.8,
        "height": 1.9,
        "status": "free",
    },
    {
        "garage_number": "36",
        "brand": "ГАЗ 2705",
        "driver": "Бумбуль В.З.",
        "gos_number": "AI 6308-4",
        "capacity": 1350.0,
        "length": 3.1,
        "width": 1.8,
        "height": 1.9,
        "status": "free",
    },
    {
        "garage_number": "37",
        "brand": "МАЗ 4371 З2",
        "driver": "Мартусевич Д.Е.",
        "gos_number": "AI 9499-4",
        "capacity": 4300.0,
        "length": 5.2,
        "width": 2.5,
        "height": 2.9,
        "status": "free",
    },
    {
        "garage_number": "39",
        "brand": "МАЗ 5440 А8",
        "driver": "Лисовский А.Э.",
        "gos_number": "AI 8218-4",
        "capacity": 10350.0,
        "length": 13.6,
        "width": 2.45,
        "height": 4.0,
        "status": "free",
    },
    {
        "garage_number": "40",
        "brand": "МАЗ 5440 С9",
        "driver": "Кохоновский В.З.",
        "gos_number": "АН 7177-4",
        "capacity": 10500.0,
        "length": 13.6,
        "width": 2.5,
        "height": 4.0,
        "status": "free",
    },
    {
        "garage_number": "60",
        "brand": "МАЗ 5551",
        "driver": "Медовский И.С.",
        "gos_number": "АМ 4794-4",
        "capacity": 10000.0,
        "length": 6.0,
        "width": 2.5,
        "height": 3.0,
        "status": "free",
    },
]

with app.app_context():
    db.create_all()

    if Vehicle.query.count() == 0:
        for veh in sample_vehicles:
            new_vehicle = Vehicle(
                garage_number=veh["garage_number"],
                brand=veh["brand"],
                driver=veh["driver"],
                gos_number=veh["gos_number"],
                capacity=veh["capacity"],
                length=veh["length"],
                width=veh["width"],
                height=veh["height"],
                status=veh["status"],
            )
            db.session.add(new_vehicle)
        db.session.commit()
        print("Sample vehicles added to the database.")
    else:
        print("Database already has vehicles. Skipping insertion.")
